version: "3.9"
services:
  server:
    container_name: lesson_9_app
    image: shuricans/app:lesson_09
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/lesson_9"
      spring.datasource.username: postgres
      spring.datasource.password: 123
    networks:
      default:

networks:
  default:
    external:
      name: db
